/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cgpa_calculator;
import javax.swing.JOptionPane;

/**
 *
 * @author Neamot
 */
public class Main_frame extends javax.swing.JFrame {
      double  gpa;
        double credit;
        double cgpa;
           double   mul=1;
         double  total_credit=0;
         double total_mul=0;
        int i=2;
        public void calculated(){
             
             
                   jLabelnumgpa.setText(i+":");
                   jLabelcredit.setText(i+":");
                   i++;
              
            
        
        
            gpa=Double.parseDouble((String) jComboBoxgpa.getSelectedItem());//4,4
        System.out.println("Input start : gap of subject: "+gpa);
        credit=Double.parseDouble((String) jComboBoxcredit.getSelectedItem());//3,3
        System.out.println("Input start : credit of subject: "+gpa);
        
        mul=(gpa*credit);//12.12
        total_mul=mul+total_mul;//12,24
        
        //System.out.println(mul);
        total_credit=credit+total_credit;//3,6
        
        cgpa=total_mul/total_credit;//4
            System.out.println("OUtput start: cgpa of given sub and credit"+cgpa);//4
    
       
        }
        

    /**
     * Creates new form Main_frame
     */
    public Main_frame() {
        initComponents();
        //jButton_submit.setVisible(false);
        //showcgpa.setVisible(true);
                //result.setVisible(true);
        this.setTitle("CGPA Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainbackground = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Calculateyourcgpa = new javax.swing.JLabel();
        totalsubject = new javax.swing.JLabel();
        jComboBoxcredit = new javax.swing.JComboBox<>();
        jComboBoxtotalsub = new javax.swing.JComboBox<>();
        entersubjectgpa = new javax.swing.JLabel();
        entercreditsub = new javax.swing.JLabel();
        jComboBoxgpa = new javax.swing.JComboBox<>();
        showcgpa = new javax.swing.JLabel();
        jButton_submit = new javax.swing.JButton();
        jLabelnumgpa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelcredit = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        developer = new javax.swing.JLabel();
        copyright = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_reset = new javax.swing.JButton();
        jButton_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainbackground.setBackground(new java.awt.Color(6, 245, 245));
        mainbackground.setAutoscrolls(true);
        mainbackground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainbackground.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        Calculateyourcgpa.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Calculateyourcgpa.setForeground(new java.awt.Color(255, 255, 255));
        Calculateyourcgpa.setText("Calculate your CGPA ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Calculateyourcgpa)
                .addGap(223, 223, 223))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Calculateyourcgpa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        totalsubject.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalsubject.setText("Enter Total number of  your Subject :");

        jComboBoxcredit.setEditable(true);
        jComboBoxcredit.setFont(totalsubject.getFont());
        jComboBoxcredit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2", "2.5", "3", "3.5", "4", " " }));
        jComboBoxcredit.setEnabled(false);
        jComboBoxcredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxcreditActionPerformed(evt);
            }
        });

        jComboBoxtotalsub.setEditable(true);
        jComboBoxtotalsub.setFont(jComboBoxcredit.getFont());
        jComboBoxtotalsub.setMaximumRowCount(12);
        jComboBoxtotalsub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBoxtotalsub.setAutoscrolls(true);
        jComboBoxtotalsub.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jComboBoxtotalsubComponentAdded(evt);
            }
        });
        jComboBoxtotalsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtotalsubActionPerformed(evt);
            }
        });

        entersubjectgpa.setFont(totalsubject.getFont());
        entersubjectgpa.setText("Enter    GPA of Subject");
        entersubjectgpa.setEnabled(false);

        entercreditsub.setFont(totalsubject.getFont());
        entercreditsub.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        entercreditsub.setText("Enter Credit of Subject");
        entercreditsub.setEnabled(false);

        jComboBoxgpa.setEditable(true);
        jComboBoxgpa.setFont(jComboBoxcredit.getFont());
        jComboBoxgpa.setMaximumRowCount(10);
        jComboBoxgpa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4.00", "3.75", "3.50", "3.25", "3.00", "2.75", "2.50", "2.25", "2.00", "0.00" }));
        jComboBoxgpa.setSelectedIndex(9);
        jComboBoxgpa.setAutoscrolls(true);
        jComboBoxgpa.setEnabled(false);
        jComboBoxgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxgpaActionPerformed(evt);
            }
        });

        showcgpa.setFont(Calculateyourcgpa.getFont());
        showcgpa.setForeground(new java.awt.Color(255, 0, 0));
        showcgpa.setText("Your Calculated  CGPA :");
        showcgpa.setEnabled(false);

        jButton_submit.setBackground(new java.awt.Color(0, 0, 255));
        jButton_submit.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jButton_submit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_submit.setText("Submit");
        jButton_submit.setEnabled(false);
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });

        jLabelnumgpa.setFont(entersubjectgpa.getFont());

        jLabelcredit.setFont(entersubjectgpa.getFont());

        result.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        result.setForeground(new java.awt.Color(204, 0, 0));
        result.setEnabled(false);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        developer.setText("Developed by Naim");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(developer, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(developer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        copyright.setBackground(new java.awt.Color(102, 102, 255));
        copyright.setForeground(new java.awt.Color(102, 255, 255));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("All copyright reserve @2020 Bsfmstu");

        javax.swing.GroupLayout copyrightLayout = new javax.swing.GroupLayout(copyright);
        copyright.setLayout(copyrightLayout);
        copyrightLayout.setHorizontalGroup(
            copyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, copyrightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        copyrightLayout.setVerticalGroup(
            copyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jButton_reset.setBackground(new java.awt.Color(0, 0, 204));
        jButton_reset.setFont(jButton_submit.getFont());
        jButton_reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_reset.setText("Reset");
        jButton_reset.setEnabled(false);
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jButton_close.setBackground(new java.awt.Color(204, 0, 0));
        jButton_close.setFont(jButton_reset.getFont());
        jButton_close.setForeground(jButton_reset.getForeground());
        jButton_close.setText("Close");
        jButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainbackgroundLayout = new javax.swing.GroupLayout(mainbackground);
        mainbackground.setLayout(mainbackgroundLayout);
        mainbackgroundLayout.setHorizontalGroup(
            mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainbackgroundLayout.createSequentialGroup()
                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainbackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalsubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxtotalsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainbackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainbackgroundLayout.createSequentialGroup()
                                .addComponent(entersubjectgpa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelnumgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainbackgroundLayout.createSequentialGroup()
                                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(showcgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_close, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainbackgroundLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(entercreditsub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelcredit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainbackgroundLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxcredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))))
                .addGap(194, 194, 194))
            .addGroup(mainbackgroundLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainbackgroundLayout.setVerticalGroup(
            mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainbackgroundLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxtotalsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(entersubjectgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelnumgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainbackgroundLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entercreditsub)
                            .addComponent(jLabelcredit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxcredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showcgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_reset, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(mainbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        String str=jComboBoxtotalsub.getSelectedItem().toString();
        int x=Integer.parseInt(str);

        if(y!=x){

            calculated();

            if(y==(x-1)){
                jButton_submit.setVisible(false);
                //following  code can change the layout 
                //totalsubject.setVisible(false);
                //jComboBoxtotalsub.setVisible(false);
                
                //for hide these element
                 entersubjectgpa.setVisible(false);
                jLabelnumgpa.setText("");
                jComboBoxgpa.setVisible(false);
                //for hide this element
                entercreditsub.setVisible(false);
                jLabelcredit.setText("");
                jComboBoxcredit.setVisible(false);
                //showing reset button and the result
                showcgpa.setVisible(true);
                result.setVisible(true);
                result.setEnabled(true);
                showcgpa.setEnabled(true);
                System.out.println("Output start: Final CGPA : "+cgpa);
                result.setText(Double.toString(cgpa));
                //System.out.println("result enable");
                jButton_submit.setEnabled(false);
                jButton_reset.setEnabled(true);
            }
            y++;

        }

        else{
            jButton_submit.setEnabled(false);
            JOptionPane.showMessageDialog(null, "You already Entered Total number of subject");
            //System.out.println("you finished your task");
        }

       // System.out.println(y);

    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jComboBoxgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxgpaActionPerformed

        if(jComboBoxgpa.getSelectedItem()!=""){
            entercreditsub.setEnabled(true);
            jComboBoxcredit.setEnabled(true);

        }
        else
         {
            JOptionPane.showMessageDialog(null, "Please Enter GPA  of subject");
        }
        
    }//GEN-LAST:event_jComboBoxgpaActionPerformed

    private void jComboBoxtotalsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtotalsubActionPerformed

        if(jComboBoxtotalsub.getSelectedItem()!=""){
            entersubjectgpa.setEnabled(true);
            jComboBoxgpa.setEnabled(true);
            int i=1;

            jLabelnumgpa.setText(i+":");
            jLabelcredit.setText(i+":");
            i++;

            totalsubject.setEnabled(false);
            jComboBoxtotalsub.setEnabled(false);

        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Total number of subject");
        }

    }//GEN-LAST:event_jComboBoxtotalsubActionPerformed

    private void jComboBoxtotalsubComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jComboBoxtotalsubComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxtotalsubComponentAdded

    private void jComboBoxcreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxcreditActionPerformed
        jButton_submit.setVisible(true);
        jButton_submit.setEnabled(true);
    }//GEN-LAST:event_jComboBoxcreditActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
      
      new Main_frame().setVisible(true);
         //obj.setVisible(false); 
         this.dispose();
        //System.exit(0);
        
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closeActionPerformed
       System.exit(0);
       //this.setDefaultCloseOperation(0);
    }//GEN-LAST:event_jButton_closeActionPerformed
     public int y=0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new Main_frame().setVisible(true);
                //obj.;        
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calculateyourcgpa;
    private javax.swing.JPanel copyright;
    private javax.swing.JLabel developer;
    private javax.swing.JLabel entercreditsub;
    private javax.swing.JLabel entersubjectgpa;
    private javax.swing.JButton jButton_close;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JComboBox<String> jComboBoxcredit;
    private javax.swing.JComboBox<String> jComboBoxgpa;
    private javax.swing.JComboBox<String> jComboBoxtotalsub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelcredit;
    private javax.swing.JLabel jLabelnumgpa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainbackground;
    private javax.swing.JLabel result;
    private javax.swing.JLabel showcgpa;
    private javax.swing.JLabel totalsubject;
    // End of variables declaration//GEN-END:variables
}
